#!/bin/bash

# The scripting addition must be loaded manually if running Big Sur.
# For this to work a sudoers file has been created for yabai specifically.
# you can find it in /private/etc/sudoers.d/yabai.
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# --- Layout: defines the default behaviour for the new spaces (bsp or float)
#           Can be configured for a per-space basis
#               yabai -m config --space n layout float
#               yabai -m config layout bsp
yabai -m config layout float

# Where new windows spawn (default right/bottom split)
#       Left/Top
#yabai -m config window_placement first_child
#       Right/Bottom
yabai -m config window_placement second_child


# --- Padding Gaps and Splits

yabai -m config top_padding     0
yabai -m config bottom_padding  0
yabai -m config left_padding    0
yabai -m config right_padding   0
yabai -m config window_gap      0
# Per space basis
#   yabai -m config --space n window_gap 0

yabai -m config auto_balance on
yabai -m config split_ratio  0.5

# --- Mouse Support
yabai -m config mouse_modifier 0x73
yabai -m config mouse_action1 move # left-click
yabai -m config mouse_action2 resize # right-click

# autofocus: window get focused, but not raised
# autoraise: as if it was clicked on
# both disabled with modifier (to access menu items)
yabai -m config focus_follows_mouse off

# mouse get moved to the center of the newly focused window
yabai -m config mouse_follows_focus off


# --- Windows Modifications
# floating windows are always on top
yabai -m config window_topmost on

# modify window shadows (options: on, off, float)
yabai -m config window_shadow float

# window opacity
# example: render all unfocused windows with 90% opacity
yabai -m config window_opacity off
yabai -m config window_opacity_duration 0.0
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 1.0

# window border
#  - width has unit 1pt
#  - colors for borders are in the format AARRGGBB with hex values
#  - active means focused window, normal means unfocused window, insert means selected window
yabai -m config window_border off
yabai -m config window_border_width 2
yabai -m config active_window_border_color  0xffc27000
yabai -m config normal_window_border_color 0xff292929


# statusbar
yabai -m config external_bar main:24:0

# --- Signals
# Flashfocus emulation, on window focus quickly change the opacity
# yabai -m signal --add event=window_focused label="flashfocus" \
    # action='/Users/ghyatzo/.local/bin/flashfocus $YABAI_WINDOW_ID'

# Ubersicht bar refresh on display/space change
# Refresh spaces widget on space change
yabai -m signal --add event=space_changed action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"nibar-spaces-jsx\"'"
yabai -m signal --add event=space_changed action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"nibar-windows-jsx\"'"
# Refresh process widget on when an application window is closed
yabai -m signal --add event=window_destroyed action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"nibar-windows-jsx\"'"
yabai -m signal --add event=window_created action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"nibar-windows-jsx\"'"
yabai -m signal --add event=window_focused action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"nibar-windows-jsx\"'"
yabai -m signal --add event=window_moved action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"nibar-windows-jsx\"'"
# --- Rules

yabai -m rule --add label="spotify-fullscreen" \
    app="^Spotify$" \
    native-fullscreen=on
yabai -m rule --add label="notepad-terminal-dimentions" \
    app="^kitty" \
    title="notepad" \
    manage=off \
    sticky=on \
    topmost=on \
    border=on \
    grid=4:4:1:1:2:2


# --- Rules --- Disable Manage/Fix opacity
yabai -m rule --add label="finder-copy" \
    app="^Finder$" \
    title="Copia" \
    manage=off
yabai -m rule --add label="finder-quick-look" \
    app="^Finder$" \
    title="^Info.*" \
    manage=off
yabai -m rule --add label="safari-opacity" \
    app="^Safari$" \
    opacity=1
yabai -m rule --add label="skim-opacity" \
    app="^Skim$" \
    opacity=1
yabai -m rule --add label="iina-float" \
    app="^IINA$" \
    manage=off \
    opacity=1
yabai -m rule --add label="system-preference-float" \
    app="^Preferenze\ di\ Sistema$" \
    manage=off \
    opacity=1
yabai -m rule --add label="julia-terminal-plots" \
    app="GKSTerm" \
    title="GKSTerm" \
    manage=off \
    opacity=1
yabai -m rule --add label="Matlab-windows" \
    app="MATLAB" \
    manage=off
yabai -m rule --add label="world-of-warcraft" \
    app="Wow" \
    title="World of Warcraft" \
    manage=off
echo "yabai config loaded..."
